using System;
using System.Collections.Generic;
using System.Threading;
using Cysharp.Threading.Tasks;
using UnityEngine;

public class EnemySpawner : MonoBehaviour
{
    private const int LowTierStartIndex = 0;
    private const int LowTierCount = 3;
    private const int AdvancedTierStartIndex = 3;
    private const int AdvancedTierCount = 3;
    private const int MinimumAdvancedEnemiesAfterFirstBoss = 3;
    private const int LowTierBurstCountAfterSecondBoss = 5;
    private const float LowTierWeightAfterFirstBoss = 0.8f;

    [Header("Auto Generation")]
    public StageGeneratorSO stageConfig;

    [Serializable]
    public class SpawnGroup
    {
        public EnemyWaveData waveData;
        public float delay;
    }

    [Serializable]
    public class Stage
    {
        public SpawnGroup[] groups;
        public bool loop;
    }

    public Stage[] stages;

    [Header("Options")]
    public bool autoStart = true;
    public bool useAutoGeneration = true;
    public GameObject warning;
    public EmergencyWarningUI emergencyWarningUI;
    public float emergencySpeedThreshold = 8f;
    public float emergencyExplosionDamageThreshold = 30f;

    private CancellationTokenSource cts;
    private StageSpawnPlanner spawnPlanner;

    private readonly struct DeferredLastEnemySpawn
    {
        public DeferredLastEnemySpawn(EnemyDataSO enemyData, float spawnTime)
        {
            EnemyData = enemyData;
            SpawnTime = spawnTime;
        }

        public EnemyDataSO EnemyData { get; }
        public float SpawnTime { get; }
    }

    private void Start()
    {
        spawnPlanner = new StageSpawnPlanner(stageConfig);
        EnsureEmergencyWarningUI();

        int startStage = StageCounter.Instance != null ? Mathf.Max(1, StageCounter.Instance.StageCount) : 1;
        if (autoStart)
        {
            StartStage(startStage);
        }
    }

    public void StartStage(int stageIndex)
    {
        StopSpawning();
        cts = new CancellationTokenSource();
        spawnPlanner = new StageSpawnPlanner(stageConfig);

        if (useAutoGeneration && stageConfig != null)
        {
            SpawnAutoGeneratedStage(stageIndex, cts.Token).Forget();
        }
        else if (stages != null && stageIndex >= 0 && stageIndex < stages.Length)
        {
            SpawnStageAsync(stages[stageIndex], cts.Token).Forget();
        }
    }

    public void StopSpawning()
    {
        if (cts == null)
        {
            return;
        }

        if (!cts.IsCancellationRequested)
        {
            cts.Cancel();
        }

        cts.Dispose();
        cts = null;
    }

    private async UniTaskVoid SpawnAutoGeneratedStage(int stageNum, CancellationToken token)
    {
        try
        {
            if (stageConfig.IsBossStage(stageNum) && warning != null)
            {
                warning.SetActive(true);
            }

            if (stageConfig.IsBossStage(stageNum))
            {
                await SpawnBossStage(stageNum, token);
            }
            else
            {
                await SpawnNormalStage(stageNum, token);
            }
        }
        catch (OperationCanceledException)
        {
        }
    }

    private async UniTask SpawnNormalStage(int stageNum, CancellationToken token)
    {
        int scalingStage = GetEnemyScalingStage(stageNum);
        int enemyCount = stageConfig.GetEnemyCount(scalingStage);
        float spawnInterval = stageConfig.GetSpawnInterval(scalingStage);
        float difficulty = stageConfig.GetDifficulty(scalingStage);

        if (stageConfig.normalEnemyPool == null || stageConfig.normalEnemyPool.Length == 0)
        {
            Debug.LogError("normalEnemyPool is empty.");
            return;
        }

        List<EnemyDataSO> spawnList = BuildNormalEnemySequence(scalingStage, difficulty, enemyCount);
        if (spawnList.Count == 0)
        {
            Debug.LogWarning($"No valid enemy prefab was found for stage {stageNum}. Stage clear cannot be assigned.");
            return;
        }

        for (int i = 0; i < spawnList.Count; i++)
        {
            token.ThrowIfCancellationRequested();

            EnemyDataSO selectedEnemy = spawnList[i];

            ShowEmergencyWarningIfNeeded(selectedEnemy);
            GameObject spawned = Instantiate(selectedEnemy.prefab, transform.position, Quaternion.identity);
            EnemyController enemy = spawned.GetComponent<EnemyController>();
            if (enemy != null)
            {
                enemy.enemyData = selectedEnemy;
                enemy.isLastEnemy = i == spawnList.Count - 1;
            }

            await UniTask.Delay((int)(spawnInterval * 1000f), cancellationToken: token);
        }
    }

    private async UniTask SpawnBossStage(int stageNum, CancellationToken token)
    {
        StageSpawnPlan plan = spawnPlanner.CreatePlan(stageNum);
        int scalingStage = GetEnemyScalingStage(stageNum);
        float spawnInterval = stageConfig.GetSpawnInterval(scalingStage);
        float difficulty = stageConfig.GetDifficulty(scalingStage);

        if (stageConfig.normalEnemyPool != null && stageConfig.normalEnemyPool.Length > 0)
        {
            List<EnemyDataSO> minions = BuildNormalEnemySequence(scalingStage, difficulty, plan.MinionCount);
            if (plan.MarkLastMinionAsStageEnd && minions.Count == 0)
            {
                Debug.LogWarning($"No valid minion prefab was found for boss stage {stageNum}. Stage clear cannot be assigned.");
                return;
            }

            for (int i = 0; i < minions.Count; i++)
            {
                token.ThrowIfCancellationRequested();
                EnemyDataSO minionData = minions[i];

                ShowEmergencyWarningIfNeeded(minionData);
                GameObject spawned = Instantiate(minionData.prefab, transform.position, Quaternion.identity);
                EnemyController enemy = spawned.GetComponent<EnemyController>();
                if (enemy != null)
                {
                    enemy.enemyData = minionData;
                    enemy.isLastEnemy = plan.MarkLastMinionAsStageEnd && i == minions.Count - 1;
                }

                await UniTask.Delay((int)(spawnInterval * 1000f), cancellationToken: token);
            }
        }

        if (!plan.HasBoss)
        {
            Debug.LogWarning($"Boss data is missing for stage {stageNum}. The last minion will end the stage.");
            return;
        }

        token.ThrowIfCancellationRequested();
        EnemyDataSO bossData = plan.BossData;

        await UniTask.Delay(2000, cancellationToken: token);

        ShowEmergencyWarningIfNeeded(bossData);
        GameObject bossObject = Instantiate(bossData.prefab, transform.position, Quaternion.identity);
        EnemyController bossEnemy = bossObject.GetComponent<EnemyController>();
        if (bossEnemy != null)
        {
            bossEnemy.enemyData = bossData;
            bossEnemy.isLastEnemy = true;
        }
    }

    private int GetEnemyScalingStage(int stageNum)
    {
        if (StageFlowManager.Instance != null)
        {
            return Mathf.Max(1, StageFlowManager.Instance.EnemyScalingStage);
        }

        return Mathf.Max(1, stageNum);
    }

    private List<EnemyDataSO> BuildNormalEnemySequence(int stageNum, float difficulty, int enemyCount)
    {
        List<EnemyDataSO> sequence = new List<EnemyDataSO>();
        EnemyDataSO[] pool = stageConfig.normalEnemyPool;
        if (pool == null || pool.Length == 0 || enemyCount <= 0)
        {
            return sequence;
        }

        int bossKillCount = StatusManager.Instance != null ? StatusManager.Instance.bossKillCount : 0;
        if (bossKillCount <= 0)
        {
            FillRandomEnemies(sequence, pool, LowTierStartIndex, LowTierCount, enemyCount);
            return sequence;
        }

        if (bossKillCount == 1)
        {
            int advancedTarget = Mathf.Min(MinimumAdvancedEnemiesAfterFirstBoss, enemyCount);
            FillPreferredEnemies(sequence, pool, AdvancedTierStartIndex, AdvancedTierCount, LowTierStartIndex, LowTierCount, advancedTarget);

            while (sequence.Count < enemyCount)
            {
                bool preferLowTier = UnityEngine.Random.value < LowTierWeightAfterFirstBoss;
                if (preferLowTier)
                {
                    if (!TryAddPreferredEnemy(sequence, pool, LowTierStartIndex, LowTierCount, AdvancedTierStartIndex, AdvancedTierCount))
                    {
                        break;
                    }
                }
                else
                {
                    if (!TryAddPreferredEnemy(sequence, pool, AdvancedTierStartIndex, AdvancedTierCount, LowTierStartIndex, LowTierCount))
                    {
                        break;
                    }
                }
            }

            ShuffleSequence(sequence);
            return sequence;
        }

        int burstCount = Mathf.Min(LowTierBurstCountAfterSecondBoss, enemyCount);
        int advancedCount = Mathf.Max(0, enemyCount - burstCount);
        FillPreferredEnemies(sequence, pool, AdvancedTierStartIndex, AdvancedTierCount, LowTierStartIndex, LowTierCount, advancedCount);

        List<EnemyDataSO> lowTierBurst = new List<EnemyDataSO>();
        FillRandomEnemies(lowTierBurst, pool, LowTierStartIndex, LowTierCount, burstCount);
        int insertIndex = sequence.Count > 0 ? UnityEngine.Random.Range(0, sequence.Count + 1) : 0;
        sequence.InsertRange(insertIndex, lowTierBurst);

        while (sequence.Count < enemyCount)
        {
            if (!TryAddPreferredEnemy(sequence, pool, AdvancedTierStartIndex, AdvancedTierCount, LowTierStartIndex, LowTierCount))
            {
                break;
            }
        }

        return sequence;
    }

    private void FillPreferredEnemies(
        List<EnemyDataSO> sequence,
        EnemyDataSO[] pool,
        int preferredStart,
        int preferredCount,
        int fallbackStart,
        int fallbackCount,
        int targetCount)
    {
        while (sequence.Count < targetCount)
        {
            if (!TryAddPreferredEnemy(sequence, pool, preferredStart, preferredCount, fallbackStart, fallbackCount))
            {
                break;
            }
        }
    }

    private void FillRandomEnemies(List<EnemyDataSO> sequence, EnemyDataSO[] pool, int startIndex, int count, int targetCount)
    {
        while (sequence.Count < targetCount)
        {
            if (!TryAddRandomEnemy(sequence, pool, startIndex, count))
            {
                break;
            }
        }
    }

    private bool TryAddPreferredEnemy(
        List<EnemyDataSO> sequence,
        EnemyDataSO[] pool,
        int preferredStart,
        int preferredCount,
        int fallbackStart,
        int fallbackCount)
    {
        if (TryAddRandomEnemy(sequence, pool, preferredStart, preferredCount))
        {
            return true;
        }

        return TryAddRandomEnemy(sequence, pool, fallbackStart, fallbackCount);
    }

    private bool TryAddRandomEnemy(List<EnemyDataSO> sequence, EnemyDataSO[] pool, int startIndex, int count)
    {
        EnemyDataSO enemy = GetRandomValidEnemy(pool, startIndex, count);
        if (enemy == null)
        {
            return false;
        }

        sequence.Add(enemy);
        return true;
    }

    private EnemyDataSO GetRandomValidEnemy(EnemyDataSO[] pool, int startIndex, int count)
    {
        int availableCount = CountValidEnemies(pool, startIndex, count);
        if (availableCount <= 0)
        {
            return null;
        }

        int selectedOffset = UnityEngine.Random.Range(0, availableCount);
        int endIndex = Mathf.Min(pool.Length, startIndex + count);
        for (int i = Mathf.Max(0, startIndex); i < endIndex; i++)
        {
            EnemyDataSO enemy = pool[i];
            if (enemy == null || enemy.prefab == null)
            {
                continue;
            }

            if (selectedOffset == 0)
            {
                return enemy;
            }

            selectedOffset--;
        }

        return null;
    }

    private int CountValidEnemies(EnemyDataSO[] pool, int startIndex, int count)
    {
        if (pool == null || count <= 0 || startIndex >= pool.Length)
        {
            return 0;
        }

        int validCount = 0;
        int endIndex = Mathf.Min(pool.Length, startIndex + count);
        for (int i = Mathf.Max(0, startIndex); i < endIndex; i++)
        {
            EnemyDataSO enemy = pool[i];
            if (enemy != null && enemy.prefab != null)
            {
                validCount++;
            }
        }

        return validCount;
    }

    private void ShuffleSequence(List<EnemyDataSO> sequence)
    {
        for (int i = sequence.Count - 1; i > 0; i--)
        {
            int swapIndex = UnityEngine.Random.Range(0, i + 1);
            (sequence[i], sequence[swapIndex]) = (sequence[swapIndex], sequence[i]);
        }
    }

    private async UniTaskVoid SpawnStageAsync(Stage stage, CancellationToken token)
    {
        if (stage == null || stage.groups == null)
        {
            return;
        }

        try
        {
            do
            {
                List<DeferredLastEnemySpawn> deferredLastEnemySpawns = new List<DeferredLastEnemySpawn>();
                bool hasConfiguredLastEnemy = HasConfiguredLastEnemy(stage);
                EnemyWaveData.SpawnData fallbackLastSpawn = hasConfiguredLastEnemy ? null : FindFallbackLastSpawn(stage);

                for (int i = 0; i < stage.groups.Length; i++)
                {
                    SpawnGroup group = stage.groups[i];
                    token.ThrowIfCancellationRequested();
                    if (group == null || group.waveData == null)
                    {
                        continue;
                    }

                    await UniTask.Delay((int)(group.delay * 1000f), cancellationToken: token);
                    token.ThrowIfCancellationRequested();
                    await SpawnWaveAsync(group.waveData, token, deferredLastEnemySpawns, fallbackLastSpawn);
                }

                if (hasConfiguredLastEnemy)
                {
                    SpawnDeferredLastEnemies(deferredLastEnemySpawns, token);
                }
                else if (fallbackLastSpawn == null)
                {
                    Debug.LogWarning("No valid spawn was found for this manual stage. Stage clear cannot be assigned.");
                }

                if (stage.loop)
                {
                    await UniTask.Delay(1000, cancellationToken: token);
                }
            }
            while (stage.loop && !token.IsCancellationRequested);
        }
        catch (OperationCanceledException)
        {
        }
    }

    private async UniTask SpawnWaveAsync(
        EnemyWaveData wave,
        CancellationToken token,
        List<DeferredLastEnemySpawn> deferredLastEnemySpawns,
        EnemyWaveData.SpawnData fallbackLastSpawn)
    {
        float startTime = Time.time;

        for (int i = 0; i < wave.spawns.Length; i++)
        {
            EnemyWaveData.SpawnData data = wave.spawns[i];
            token.ThrowIfCancellationRequested();
            if (data == null || data.enemyData == null || data.enemyData.prefab == null)
            {
                continue;
            }

            if (data.LastEnemy)
            {
                deferredLastEnemySpawns?.Add(new DeferredLastEnemySpawn(data.enemyData, data.spawnTime));
                continue;
            }

            float wait = Mathf.Max(0f, data.spawnTime - (Time.time - startTime));
            if (wait > 0f)
            {
                await UniTask.Delay((int)(wait * 1000f), cancellationToken: token);
            }

            token.ThrowIfCancellationRequested();
            ShowEmergencyWarningIfNeeded(data.enemyData);
            GameObject spawned = Instantiate(data.enemyData.prefab, transform.position, Quaternion.identity);
            EnemyController enemy = spawned.GetComponent<EnemyController>();
            if (enemy != null)
            {
                enemy.enemyData = data.enemyData;
                enemy.SetLastEnemy(data.LastEnemy || ReferenceEquals(data, fallbackLastSpawn));
            }
        }
    }

    private void SpawnDeferredLastEnemies(List<DeferredLastEnemySpawn> deferredLastEnemySpawns, CancellationToken token)
    {
        if (deferredLastEnemySpawns == null || deferredLastEnemySpawns.Count == 0)
        {
            Debug.LogWarning("No LastEnemy spawn was found for this manual stage. Stage clear will not trigger until a LastEnemy is configured.");
            return;
        }

        deferredLastEnemySpawns.Sort((a, b) => a.SpawnTime.CompareTo(b.SpawnTime));

        for (int i = 0; i < deferredLastEnemySpawns.Count; i++)
        {
            token.ThrowIfCancellationRequested();
            DeferredLastEnemySpawn data = deferredLastEnemySpawns[i];
            if (data.EnemyData == null || data.EnemyData.prefab == null)
            {
                continue;
            }

            ShowEmergencyWarningIfNeeded(data.EnemyData);
            GameObject spawned = Instantiate(data.EnemyData.prefab, transform.position, Quaternion.identity);
            EnemyController enemy = spawned.GetComponent<EnemyController>();
            if (enemy != null)
            {
                enemy.enemyData = data.EnemyData;
                enemy.SetLastEnemy(IsLastValidDeferredSpawn(deferredLastEnemySpawns, i));
            }
        }
    }

    private static bool HasConfiguredLastEnemy(Stage stage)
    {
        if (stage == null || stage.groups == null)
        {
            return false;
        }

        for (int i = 0; i < stage.groups.Length; i++)
        {
            SpawnGroup group = stage.groups[i];
            if (group == null || group.waveData == null || group.waveData.spawns == null)
            {
                continue;
            }

            for (int j = 0; j < group.waveData.spawns.Length; j++)
            {
                EnemyWaveData.SpawnData spawn = group.waveData.spawns[j];
                if (spawn != null && spawn.enemyData != null && spawn.enemyData.prefab != null && spawn.LastEnemy)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static EnemyWaveData.SpawnData FindFallbackLastSpawn(Stage stage)
    {
        if (stage == null || stage.groups == null)
        {
            return null;
        }

        EnemyWaveData.SpawnData fallback = null;
        for (int i = 0; i < stage.groups.Length; i++)
        {
            SpawnGroup group = stage.groups[i];
            if (group == null || group.waveData == null || group.waveData.spawns == null)
            {
                continue;
            }

            for (int j = 0; j < group.waveData.spawns.Length; j++)
            {
                EnemyWaveData.SpawnData spawn = group.waveData.spawns[j];
                if (spawn != null && spawn.enemyData != null && spawn.enemyData.prefab != null)
                {
                    fallback = spawn;
                }
            }
        }

        return fallback;
    }

    private static bool IsLastValidDeferredSpawn(List<DeferredLastEnemySpawn> deferredLastEnemySpawns, int index)
    {
        for (int i = index + 1; i < deferredLastEnemySpawns.Count; i++)
        {
            EnemyDataSO enemyData = deferredLastEnemySpawns[i].EnemyData;
            if (enemyData != null && enemyData.prefab != null)
            {
                return false;
            }
        }

        return true;
    }

    private void ShowEmergencyWarningIfNeeded(EnemyDataSO enemyData)
    {
        if (!ShouldShowEmergencyWarning(enemyData))
        {
            return;
        }

        EnsureEmergencyWarningUI();
        if (emergencyWarningUI != null)
        {
            emergencyWarningUI.Show();
        }
    }

    private bool ShouldShowEmergencyWarning(EnemyDataSO enemyData)
    {
        if (enemyData == null)
        {
            return false;
        }

        if (enemyData.isHighlighted)
        {
            return true;
        }

        bool hasDangerousExplosion = enemyData.aiType == EnemyAIType.Bomber &&
            enemyData.explosionDamage >= emergencyExplosionDamageThreshold;
        return enemyData.speed >= emergencySpeedThreshold || hasDangerousExplosion;
    }

    private void EnsureEmergencyWarningUI()
    {
        if (emergencyWarningUI != null)
        {
            return;
        }

        emergencyWarningUI = FindFirstObjectByType<EmergencyWarningUI>(FindObjectsInactive.Include);
    }
}
